name: Rust

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-rust
        with:
          install-apt: true
          components: rustfmt
      - name: Format Check
        run: cargo fmt --check

  lint:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-rust
        with:
          install-apt: ${{ matrix.os == 'ubuntu-latest' }}
          components: clippy
      - name: Clippy Check
        run: cargo clippy --verbose --all-targets --all-features -- -D warnings

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-rust
        with:
          install-apt: ${{ matrix.os == 'ubuntu-latest' }}
      - name: Build all targets
        run: cargo build --verbose --all-targets --all-features --examples

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-rust
        with:
          install-apt: ${{ matrix.os == 'ubuntu-latest' }}
      - name: Binary tests
        run: cargo test --verbose --all-targets --all-features

  doc-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-rust
        with:
          install-apt: true
      - name: Doc tests
        run: cargo test --verbose --doc --all-features

  doc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-rust
        with:
          install-apt: true
      - name: Build documentation
        run: cargo doc --no-deps --all-features --document-private-items
